"""Notification manager for email and Slack alerts."""
import smtplib
import requests
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List, Dict, Any, Optional
from datetime import datetime

from config_manager import get_config

logger = logging.getLogger('NotificationManager')


class NotificationManager:
    """Send notifications via email and Slack."""

    def __init__(self):
        self.config = get_config()

    def send_alert(self, title: str, message: str, severity: str = 'Medium',
                   iocs: List[Dict] = None, threat_actors: List[str] = None):
        """Send alert via all configured channels."""

        if self.config.is_notification_enabled('email'):
            self._send_email(title, message, severity, iocs, threat_actors)

        if self.config.is_notification_enabled('slack'):
            self._send_slack(title, message, severity, iocs, threat_actors)

    def _send_email(self, title: str, message: str, severity: str,
                    iocs: List[Dict] = None, threat_actors: List[str] = None):
        """Send email notification."""
        try:
            email_config = self.config.get_notification_config('email')

            msg = MIMEMultipart()
            msg['From'] = email_config.get('from_address', '')
            msg['To'] = ', '.join(email_config.get('to_addresses', []))
            msg['Subject'] = f"[{severity}] Threat Intel Alert: {title}"

            # Build email body
            body = self._build_email_body(title, message, severity, iocs, threat_actors)
            msg.attach(MIMEText(body, 'html'))

            # Send email
            server = smtplib.SMTP(
                email_config.get('smtp_server', ''),
                email_config.get('smtp_port', 587)
            )
            server.starttls()
            server.login(email_config.get('username', ''), email_config.get('password', ''))
            server.send_message(msg)
            server.quit()

            logger.info(f"Email alert sent: {title}")

        except Exception as e:
            logger.error(f"Failed to send email alert: {e}")

    def _build_email_body(self, title: str, message: str, severity: str,
                          iocs: List[Dict] = None, threat_actors: List[str] = None) -> str:
        """Build HTML email body."""
        severity_colors = {
            'Critical': '#ff0040',
            'High': '#ff6b35',
            'Medium': '#ffbe0b',
            'Low': '#00ff88'
        }
        color = severity_colors.get(severity, '#00d4ff')

        ioc_html = ""
        if iocs:
            ioc_html = "<h3>Indicators of Compromise:</h3><ul>"
            for ioc in iocs[:10]:
                ioc_html += f"<li><code>{ioc.get('value', '')}</code> ({ioc.get('ioc_type', '')})</li>"
            ioc_html += "</ul>"

        actor_html = ""
        if threat_actors:
            actor_html = "<h3>Threat Actors:</h3><ul>"
            for actor in threat_actors:
                actor_html += f"<li>{actor}</li>"
            actor_html += "</ul>"

        return f"""
        <html>
        <body style="font-family: Arial, sans-serif; background-color: #1a1a2e; color: #ffffff; padding: 20px;">
            <div style="background-color: #16213e; padding: 20px; border-radius: 10px; border-left: 4px solid {color};">
                <h1 style="color: {color};">🛡️ Threat Intel Alert</h1>
                <h2>{title}</h2>
                <p><strong>Severity:</strong> <span style="color: {color};">{severity}</span></p>
                <p><strong>Time:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
                <hr style="border-color: #2d3748;">
                <p>{message}</p>
                {ioc_html}
                {actor_html}
                <hr style="border-color: #2d3748;">
                <p style="color: #a0aec0; font-size: 12px;">
                    This alert was generated by Threat Intel Hub.
                    <a href="#" style="color: #00d4ff;">View Dashboard</a>
                </p>
            </div>
        </body>
        </html>
        """

    def _send_slack(self, title: str, message: str, severity: str,
                    iocs: List[Dict] = None, threat_actors: List[str] = None):
        """Send Slack notification."""
        try:
            slack_config = self.config.get_notification_config('slack')
            webhook_url = slack_config.get('webhook_url', '')

            if not webhook_url:
                logger.warning("Slack webhook URL not configured")
                return

            severity_colors = {
                'Critical': '#ff0040',
                'High': '#ff6b35',
                'Medium': '#ffbe0b',
                'Low': '#00ff88'
            }
            color = severity_colors.get(severity, '#00d4ff')

            # Build Slack blocks
            blocks = [
                {
                    "type": "header",
                    "text": {
                        "type": "plain_text",
                        "text": f"🛡️ Threat Intel Alert: {title}",
                        "emoji": True
                    }
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": f"*Severity:*\n{severity}"
                        },
                        {
                            "type": "mrkdwn",
                            "text": f"*Time:*\n{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
                        }
                    ]
                },
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": message[:2000]
                    }
                }
            ]

            # Add IOCs if available
            if iocs:
                ioc_text = "\n".join([f"• `{ioc.get('value', '')}` ({ioc.get('ioc_type', '')})" for ioc in iocs[:5]])
                if len(iocs) > 5:
                    ioc_text += f"\n• _...and {len(iocs) - 5} more_"

                blocks.append({
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f"*Top IOCs:*\n{ioc_text}"
                    }
                })

            # Add threat actors if available
            if threat_actors:
                actor_text = "\n".join([f"• {actor}" for actor in threat_actors[:5]])
                blocks.append({
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f"*Threat Actors:*\n{actor_text}"
                    }
                })

            # Add action button
            blocks.append({
                "type": "actions",
                "elements": [
                    {
                        "type": "button",
                        "text": {
                            "type": "plain_text",
                            "text": "View Dashboard",
                            "emoji": True
                        },
                        "url": "http://localhost:8501",
                        "action_id": "view_dashboard"
                    }
                ]
            })

            payload = {
                "attachments": [
                    {
                        "color": color,
                        "blocks": blocks
                    }
                ]
            }

            response = requests.post(webhook_url, json=payload, timeout=10)
            response.raise_for_status()

            logger.info(f"Slack alert sent: {title}")

        except Exception as e:
            logger.error(f"Failed to send Slack alert: {e}")

    def send_critical_alert(self, intel_item: Dict):
        """Send alert for critical severity items."""
        title = intel_item.get('title', 'Unknown Threat')
        severity = intel_item.get('severity', 'Critical')

        if severity != 'Critical':
            return

        message = intel_item.get('summary', 'No summary available.')
        threat_actors = intel_item.get('threat_actors', [])

        self.send_alert(
            title=title,
            message=message,
            severity=severity,
            threat_actors=threat_actors
        )

    def send_ioc_alert(self, iocs: List[Dict], threshold: int = 5):
        """Send alert when multiple IOCs from same source are detected."""
        if len(iocs) < threshold:
            return

        title = f"Multiple IOCs Detected ({len(iocs)})"
        message = f"Detected {len(iocs)} IOCs from {iocs[0].get('source', 'Unknown')} source."

        # Group by malware family if available
        malware_families = set(ioc.get('malware_family', '') for ioc in iocs if ioc.get('malware_family'))

        self.send_alert(
            title=title,
            message=message,
            severity='High',
            iocs=iocs[:10],
            threat_actors=list(malware_families) if malware_families else None
        )


# Global notification manager instance
_notification_manager: Optional[NotificationManager] = None


def get_notification_manager() -> NotificationManager:
    """Get global notification manager instance."""
    global _notification_manager
    if _notification_manager is None:
        _notification_manager = NotificationManager()
    return _notification_manager
